### ISSUE TITLE
پیشنهاد استقرار پروژه روی هروکو

### ISSUE THREAD

**Issue by anvaari** [mhmda-83/jobyab#1]
سلام 
به نظرم ربات خیلی کاربردی هستش. پیشنهاد میکنم روی 
[Heroku](https://www.heroku.com/)
استقرارش بدی تا آدما بتونن ازش استفاده کنن.
البته من تجربه کار با تایپ و جاوا رو ندارم. اما با پایتون خیلی راحت بود. فکر کنم بتونی توی نت دربارش پیدا کنی البته خودشم مستندات خوبی داره. :)
موفق باشی

**Comment by mhmda-83** [comment]
> سلام
> به نظرم ربات خیلی کاربردی هستش. پیشنهاد میکنم روی
> [Heroku](https://www.heroku.com/)
> استقرارش بدی تا آدما بتونن ازش استفاده کنن.
> البته من تجربه کار با تایپ و جاوا رو ندارم. اما با پایتون خیلی راحت بود. فکر کنم بتونی توی نت دربارش پیدا کنی البته خودشم مستندات خوبی داره. :)
> موفق باشی

سلام متقابل
قبلا تجربه استفاده ازش رو دارم و برای دیپلوی این پروژه هم تلاش کردم ولی به دلیل استفاده از puppeteer امکان دیپلوی نبود (مشکلات زیادی داشت)

به هرحال ممنون از پیشنهادت 💙

**Comment by anvaari** [comment]
آها خیلی هم عالی. ولی خیلی کاربردی بود رباتت. خلاصه خسته نباشی 
:heart:
